import { CONSTANTS } from "./Constants"

export const CONFIG = {
  DEFAULT_PLAYER_SPEED: 1,
  DEFAULT_THIEF_SPEED: 1,
  DEFAULT_PLAYER_HEALTH: 5,
  DEFAULT_THIEF_HEALTH: 100,
  DEFAULT_TEXTURE_SIZE: 200,
  MIN_TEXTURE_SIZE: 30,
  MAX_TEXTURE_SIZE: 300,
  MAIN_APP_COLOR: "#1b2a41",
  DEFAULT_SELECTED_LEVEL: 1,
  DEFAULT_SEARCH_PRIORITY: CONSTANTS.HEALTH,
  EDITING_BORDER: "5px solid purple"
}
