export const CONFIG = {
  DEFAULT_PLAYER_SPEED: 1,
  DEFAULT_THIEF_SPEED: 1,
  DEFAULT_PLAYER_HEALTH: 5,
  DEFAULT_THIEF_HEALTH: 100,
  DEFAULT_TEXTURE_SIZE: 200,
  MIN_TEXTURE_SIZE: 50,
  MAX_TEXTURE_SIZE: 150,
  DEFAULT_HEALTH_IMPORTANCE: 0.09,
  EDITING_BORDER: "5px solid purple"
}
