import { CONSTANTS } from "./Constants"

export const CONFIG = {
  DEFAULT_PLAYER_SPEED: 1,
  DEFAULT_CHICKEN_SPEED: 0,
  DEFAULT_PLAYER_HEALTH: 5,
  DEFAULT_CHICKEN_HEALTH: 100,
  MIN_APPLICATION_HEIGHT: 450,
  MIN_APPLICATION_WIDTH: 300,
  DEFAULT_INITIAL_LEVEL: 1,
  MAIN_APP_COLOR: "#274029",
  SECONDARY_APP_COLOR: "#012622",
  DEFAULT_SELECTED_LEVEL: 1,
  DEFAULT_SEARCH_PRIORITY: CONSTANTS.SPEED,
  EDITING_BORDER: "4px solid purple"
}
